### ISSUE TITLE
Add support for `CMR-Search-After` to avoid lost / duplicated results

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/earthaccess#145]
It's possible with a paging query to receive duplicate or lost results if changes to CMR are occurring between page queries. The recommended way to avoid this is currently the `CMR-Search-After` header ("scrolling" is deprecated): https://cmr.earthdata.nasa.gov/search/site/docs/search/api.html#search-after

**Comment by betolink** [comment]
This is definitely something worth adding! right now we are using explicit pagination but is not optimal. Maybe we can couple this pagination with some lazy query evaluation see #120

**Comment by betolink** [comment]
This as implemented in v0.4.7!! thanks for the report @MattF-NSIDC !!
