### ISSUE TITLE
update docs to encourage earthaccess.login() without strategy

### ISSUE THREAD

**Issue by JessicaS11** [nsidc/earthaccess#218]
v0.5.0 added functionality for the login function to automatically try all of the strategies without requiring the user to specify each. The docs need to be updated to reflect this simplification for the user.

**Comment by jrbourbeau** [comment]
Thanks @JessicaS11. https://github.com/nsidc/earthaccess/pull/300 updates `earthaccess` to handle auth automatically if there's a `~/.netrc` file around or `EARTHDATA_*` environment variables set. We also updated the authentication section in the docs to encourage `earthaccess.login()` (w/o `strategy=`) when `~/.netrc` or `EARTHDATA_*` env vars around specified. 

I'm going to close this issue as fixed, but let me know if I'm missing something and there are other places you think should be updated too.
