### ISSUE TITLE
search_data() function does not recognize doi key

### ISSUE THREAD

**Issue by Joshdpaul** [nsidc/earthaccess#232]
Attempting to use `search_data()` and a DOI string (here, using the function's own example of `doi="10.5067/SLREF-CDRV2"` returns an unknown key error. Any assistance here would be appreciated, thanks!

```
import earthaccess
auth = earthaccess.login()
```

_some authentication lines hidden for privacy..._

```
You're now authenticated with NASA Earthdata Login
Using token with expiration date: 06/17/2023
Using user provided credentials for EDL
```

```
datasets = earthaccess.search_data(
    doi="10.5067/SLREF-CDRV2",
    cloud_hosted=True,
    temporal=("2002-01-01", "2002-12-31")
)
```
```

ValueError                                Traceback (most recent call last)
Cell In[16], line 1
----> 1 datasets = earthaccess.search_data(
      2     doi="10.5067/SLREF-CDRV2",
      3     cloud_hosted=True,
      4     temporal=("2002-01-01", "2002-12-31")
      5 )

File ~\Anaconda3\envs\earthaccess\Lib\site-packages\earthaccess\api.py:103, in search_data(count, **kwargs)
     65 def search_data(
     66     count: int = -1, **kwargs: Any
     67 ) -> List[earthaccess.results.DataGranule]:
     68     """Search dataset granules using NASA's CMR.
     69 
     70     [https://cmr.earthdata.nasa.gov/search/site/docs/search/api.html](https://cmr.earthdata.nasa.gov/search/site/docs/search/api.html)
   (...)
    101         ```
    102     """
--> 103     query = DataGranules().parameters(**kwargs)
    104     granules_found = query.hits()
    105     print(f"Granules found: {granules_found}")

File ~\Anaconda3\envs\earthaccess\Lib\site-packages\earthaccess\search.py:342, in DataGranules.parameters(self, **kwargs)
    339 for key, val in kwargs.items():
    340     # verify the key matches one of our methods
    341     if key not in methods:
--> 342         raise ValueError("Unknown key {}".format(key))
    344     # call the method
    345     if isinstance(val, tuple):

ValueError: Unknown key doi
```

**Comment by betolink** [comment]
Hi @Joshdpaul earthaccess supports 2 kind of queries, dataset queries (collections) and data queries (files), NASA CMR does not support DOI as parameters on file level queries. Perhaps what you were looking for is

```python
datasets = earthaccess.search_datasets(
    doi="10.5067/SLREF-CDRV2",
    cloud_hosted=True
)
```
which returns 0 results, after looking at the dataset I noticed that it was just deprecated by PODAAC, the version 3 DOI is 

```python
datasets = earthaccess.search_datasets(
    doi="10.5067/SLREF-CDRV3",
    cloud_hosted=True
)
```

`datasets` will be a list of the datasets found, this one returns one. If you don't want to print all the metadata you can configure the fields too. After looking at the data you should find `short_name`, or `concept_id` which are the key parameters for NASA CMR to fund you the files from a particular dataset. The next step would be to use them like in your original query:

```python
results = earthaccess.search_data(
    concept_id="C2270392799-POCLOUD",
    cloud_hosted=True,
    temporal=("2002-01-01", "2002-12-31")
)
```

that gives me 73 files that we can finally open or download, I'd recommend downloading them unless you are executing the code in AWS (us-west-2). Hopefully this answers your question.

**Comment by Joshdpaul** [comment]
Great, thank you for the clarification between the `search_data()` and `search_datasets` parameters.

**Comment by betolink** [comment]
closing this one as resolved!
