### ISSUE TITLE
is there  a detailed user manual?

### ISSUE THREAD

**Issue by lwk1542** [nsidc/earthaccess#240]
such as:
1. how to set the configuration content of .netrc file. EARTHDATA_USERNAME=[***],EARTHDATA_PASSWORD=[***]
2. What are the optional parameters for variables? I want to search MOD021KM, how to set the short_name or sensor?
3. ...

**Comment by asteiker** [comment]
@lwk1542 For 1., we have documentation on .netrc usage here: https://earthaccess.readthedocs.io/en/latest/howto/authenticate/#authentication. For 2., We have a list of arguments for data search here: https://earthaccess.readthedocs.io/en/latest/user-reference/api/api/#earthaccess.api.search_data. 

Thank you @jroebuck932 for your earlier suggestions! We miss you at NSIDC ❤️

**Comment by mfisher87** [comment]
>2., We have a list of arguments for data search here: https://earthaccess.readthedocs.io/en/latest/user-reference/api/api/#earthaccess.api.search_data.

Although those lists are incomplete at the moment! See: #345
