### ISSUE TITLE
Document count keyword in `search_data` method

### ISSUE THREAD

**Issue by andypbarrett** [nsidc/earthaccess#266]
The docstring for api.py/search_data does not contain information for `count`.

**Comment by jrbourbeau** [comment]
Thanks for the issue @andypbarrett. It looks like there's an entry for `count=` in `search_data` here 

https://github.com/nsidc/earthaccess/blob/95253c01f37048f4eea780e08be9d9dca2dd9c0d/earthaccess/api.py#L74

**Comment by MattF-NSIDC** [comment]
Looks like that information is being successfully extracted from the docstring and [shown in the docs](https://nsidc.github.io/earthaccess/user-reference/api/api/#earthaccess.api.search_data) as well. I think we can close, but feel free to re-open if we've got it all wrong, Andy!
