### ISSUE TITLE
Documentation builds not triggered when README.md, CONTRIBUTING.md, LICENCE.txt altered

### ISSUE THREAD

**Issue by mfisher87** [nsidc/earthaccess#274]
These files are symlinked into the `docs` directory, and our workflow is triggered by changes in the `docs` directory. GitHub Actions does not recognize a change to `README.md` as a change to the symlink `docs/index.md`, so if the README is changed, docs don't build. I tested this on a fork.

https://github.com/mfisher87/earthaccess/pull/4

**Comment by jrbourbeau** [comment]
Circling back here. I think the recent readthedocs work closes this issue as now we get a documentation build + preview on all PRs. I'm going to close this issue as fixed, but feel free to re-open is that's not the case @MattF-NSIDC

**Comment by mfisher87** [comment]
I think we need to clean up and simplify some GHA YAML:

- Ignore [Pull Request event](
https://github.com/nsidc/earthaccess/blob/6fbc4ae4146c399b14b9ec7e7b2333d94cb12830/.github/workflows/documentation.yml#L14-L21) - RTD does this
- Update `paths` list for push events - we want GHA to match RTD when `README.md` is changed, for example.
- Simplify [this conditional](https://github.com/nsidc/earthaccess/blob/6fbc4ae4146c399b14b9ec7e7b2333d94cb12830/.github/workflows/documentation.yml#L60-L63), should just be checking if `branch == main|documentation` - the rest is vestigial IIRC

**Comment by mfisher87** [comment]
I'm opening a quick PR so we don't have to open anything else to track that :)
