### ISSUE TITLE
`earthaccess.login()` has lots of output

### ISSUE THREAD

**Issue by jrbourbeau** [nsidc/earthaccess#283]
Running `earthaccess.login()` has the following output:

```python
In [1]: import earthaccess

In [2]: earthaccess.login()
EARTHDATA_USERNAME and EARTHDATA_PASSWORD are not set in the current environment, try setting them or use a different strategy (netrc, interactive)
You're now authenticated with NASA Earthdata Login
Using token with expiration date: 10/01/2023
Using .netrc file for EDL
Out[2]: <earthaccess.auth.Auth at 0x10769cfd0>
```

I could be totally off, but this seems like a lot of information for a successful login. In particular the 

```
EARTHDATA_USERNAME and EARTHDATA_PASSWORD are not set in the current environment, try setting them or use a different strategy (netrc, interactive)
```

could be possibly concerning for someone who's new to `earthaccess`. Maybe they see this message and think something went wrong. 

I'm curious what folks here think about having less verbose output in this case like

```python
In [1]: import earthaccess

In [2]: earthaccess.login()
You have successfully authenticated with NASA Earthdata
Out[2]: <earthaccess.auth.Auth at 0x10769cfd0>
```

or maybe even no output if the login is successful 

This is a relatively minor issue, though one I thought was still worth raising.

**Comment by MattF-NSIDC** [comment]
>no output if the login is successful

:100: 

The rest feels like it should be debug output! And the order seems kind of weird. "Using netrc" seems like it should have been printed before "Success".
