### ISSUE TITLE
Suggest `earthaccess.download` returns the full local path(s) instead of filename

### ISSUE THREAD

**Issue by andypbarrett** [nsidc/earthaccess#284]
Currently, `earthaccess.download(results, access='external')` [returns](https://github.com/nsidc/earthaccess/blob/95253c01f37048f4eea780e08be9d9dca2dd9c0d/earthaccess/store.py#L566) the `local_filename`.  For workflows in which files are downloaded to a local machine and then some analysis performed on them, it would be useful if the full path to those files were returned.  This would allow the files to be processed directly using the returned paths without having to glob the download path.   For example:

```
DOWNLOAD_PATH = Path.cwd() / "smap_data"
DOWNLOAD_PATH.mkdir(parents=True, exist_ok=True)  # creates parents if they don't exist and fails silently if path exists

smap_files = earthaccess.download(results, DOWNLOAD_PATH)
```
Then...
```
for f in smap_files:
    do_something_with(f)
```
I'm also wondering if it makes sense to return a list of `pathlib.Path` objects rather than a string.

**Comment by MattF-NSIDC** [comment]
>I'm also wondering if it makes sense to return a list of pathlib.Path objects rather than a string.

:100:  yes!

**Comment by jrbourbeau** [comment]
Thanks @andypbarrett. I'm closing this issue as https://github.com/nsidc/earthaccess/pull/317 updated `earthaccess.download(...)` to return the full local path (I ran into the same issue as you and thought the full path would be nicer) and https://github.com/nsidc/earthaccess/issues/319 should cover the remaining `pathlib.Path` portion of this issue. Though let me know if I'm missing something and we can always re-open
