### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by jrbourbeau** [nsidc/earthaccess#295]
It'd be nice if the changes in https://github.com/nsidc/earthaccess/pull/276 where included in a release. @betolink I've got bandwidth to help out with releasing if that'd be useful. Are release steps documented somewhere? (Definitely no worries if not)

**Comment by betolink** [comment]
Definitely, let me work on something that adds authenticated queries to the top level `earthaccess.search_data()` method and once that we get that PR merged we can do a release, hopefully today/tomorrow.

**Comment by jrbourbeau** [comment]
That sounds great -- thanks @betolink! Just let me know if there's anything I can do to help out

**Comment by jrbourbeau** [comment]
Closing as https://github.com/nsidc/earthaccess/releases/tag/v0.6.1 is out -- thanks @betolink
