### ISSUE TITLE
`pathlib` all the things!

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/earthaccess#319]
@betolink @jrbourbeau how do you feel about replacing all `os.path` things with `pathlib`? I'm sure there's a Ruff or other pre-commit rule we can use to ensure the whole codebase is using our preferred interface for doing pathy things. Maybe ruff or some other codemod out there can even automatically migrate us?

I don't think this is urgent of course, but it seems like a worthwhile code quality improvement to track as an issue if we all agree :)

**Comment by jhkennedy** [comment]
I'll add my support to this! I've been very happy moving over to `pathlib` primarily. There is one caveat worth keeping in mind with this package though -- `pathlib` will will normalize URL paths (`https://a/b/c` --> `https:/a/b/c`), breaking them. So, we'll just want to be careful there.

**Comment by MattF-NSIDC** [comment]
Ah, that is a weird little footgun. I've never encountered that myself, but now that you say it, of course... `https://a/b/c` is a valid posix path: colons can be in directory names and and duplicate path separators are ignored.

**Comment by MattF-NSIDC** [comment]
I think your concern is that we may be using `os.path.join` to construct URL paths, right? I haven't looked to confirm if this is true. If there are cases like this, should we use plain f-strings (or urllib) instead of `os.path` features? Using `os.path` to make URL paths is a bit of a red herring to me as a reader.

**Comment by jhkennedy** [comment]
Yeah, it's fun:
![image](https://github.com/nsidc/earthaccess/assets/7882693/19fc7ddc-0601-4796-843e-f3244ddf1875)

>  think your concern is that we may be using os.path.join to construct URL paths, right? I haven't looked to confirm if this is true. If there are cases like this, should we use plain f-strings (or urllib) instead of os.path features? Using os.path to make URL paths is a bit of a red herring to me as a reader.

It's more, the space earthaccess operates in, you might not know if you've got a local file path or an HTTP path to a file (the whole idea, is generally, users *shouldn't* care). It's just something to keep in mind when making the changes or reviewing them.

I agree, if we're constructing URLs we should be using f-strings or something like `urllib`. And for file paths, I prefer `pathlib` over `os.path`.

**Comment by jhkennedy** [comment]
Doing a quick search:
https://github.com/search?q=repo%3Ansidc%2Fearthaccess%20os.path&type=code

I don't see anywhere that `os.path` is used that isn't explicitly a local path, so this change shouldn't be an issue.

**Comment by MattF-NSIDC** [comment]
>It's more, the space earthaccess operates in, you might not know if you've got a local file path or an HTTP path to a file (the whole idea, is generally, users shouldn't care). It's just something to keep in mind when making the changes or reviewing them.

That makes total sense, thanks for pointing it out! Perhaps in situations where we don't know, we can use urllib to try and parse a protocol out of the string, and if that fails treat it like a filepath? :thinking:

**Comment by kvenkman** [comment]
I'd be happy to take a crack at this issue - could I be assigned to it? The issue seems relatively straightforward - let me know if there are any subtleties of simply swapping out `os.path` with `pathlib` that I should be aware about.

**Comment by mfisher87** [comment]
>I'd be happy to take a crack at this issue - could I be assigned to it?

Awesome! And absolutely! :) Please give me or anyone else a ping in this thread if we can provide support! Welcome :heart: 

>let me know if there are any subtleties of simply swapping out os.path with pathlib that I should be aware about.

The most useful thing for me, if you aren't already aware of it, has been [this mapping between equivalent `os.path` and `pathlib` tools](https://docs.python.org/3/library/pathlib.html#correspondence-to-tools-in-the-os-module).

**Comment by jhkennedy** [comment]
Resolved by #459
