### ISSUE TITLE
Release? 

### ISSUE THREAD

**Issue by jrbourbeau** [nsidc/earthaccess#322]
There have been some recent changes around authentication (xref https://github.com/nsidc/earthaccess/pull/300, https://github.com/nsidc/earthaccess/pull/316) and downloading data files (xref https://github.com/nsidc/earthaccess/pull/308, https://github.com/nsidc/earthaccess/pull/317, https://github.com/nsidc/earthaccess/pull/318) that I think it'd be good to push out to users. 

What do others think? cc @betolink @MattF-NSIDC

**Comment by mfisher87** [comment]
That sounds great to me! Would you be interested in releasing v0.7.0? We have a releasing section in CONTRIBUTING.md and it would be great to have another quality check on that :)

**Comment by MattF-NSIDC** [comment]
Woops! I was going through my notifications and started autopiloting, no idea why I clicked that particular button...

**Comment by jrbourbeau** [comment]
Thanks for pointing me to the release docs @MattF-NSIDC. Could you or @betolink add me on PyPI (same username as my GitHub)? 

All the PRs linked to in this issue have been merged, so I'm inclined to say we're in an okay state to release. Please chime in if I'm missing something : ) 

I'm happy to go through the release process by myself (they seem simple enough). That said, @MattF-NSIDC @betolink if either of you have time over the next day or two, I'd also be happy to hop on a call and go through things together, but no worries if not.

**Comment by betolink** [comment]
@jrbourbeau I have time tomorrow morning, I think it would be nice if we go through this at least once then any of us can do a release. I'm not sure if the docs are up to date but now it should be automatic after a manual release on Github, the one thing we haven;t automated is the automatic semver versioning when we commit to main and do new releases, I'm sure you have plenty of experience with this process and can help us improving that.

**Comment by jrbourbeau** [comment]
Sounds good, thanks. I'll reach out offline to set up a time
