### ISSUE TITLE
Switch GitHub pages from "branch" source to "actions"/API source

### ISSUE THREAD

**Issue by mfisher87** [nsidc/earthaccess#323]
I just can't stand the `gh-pages` branch. Any preferences? It's an easy migration.

**Comment by asteiker** [comment]
@mfisher87  We see that #325 was closed, but `gh-pags` branch still exists. Do we just need to close the branch to call this complete?

**Comment by mfisher87** [comment]
We can close this without making any changes. We dropped GitHub Pages for docs (effectively) and reset the `gh-pages` branch to only include a redirect to ReadTheDocs.
