### ISSUE TITLE
Unable to enter anything

### ISSUE THREAD

**Issue by Liuyi0205** [nsidc/earthaccess#326]
When I use earthaccess.login(), I can't enter earthdata password

**Comment by mfisher87** [comment]
Thanks for the report! Can you please provide some more details?

* Which version of `earthaccess` are you using?
* Are you expecting an interactive prompt to enter your credentials?
* What happens instead?

**Comment by Liuyi0205** [comment]
Sorry, I have solved it. The password just doesn't show up when I type it, but when I type it correctly, I can log in successfully.

**Comment by mfisher87** [comment]
Glad to hear everything's working for you now :) Don't hesitate to open more issues if you have any further problems!
