### ISSUE TITLE
Replace Flake8 with Ruff

### ISSUE THREAD

**Issue by mfisher87** [nsidc/earthaccess#341]

**Comment by jhkennedy** [comment]
:+1: I'll second this one; I'm in the process of switch over over most of our repositories from flake8 to ruff.

**Comment by jrbourbeau** [comment]
+1 from me too -- @jhkennedy do you have bandwidth to switch over here too?

**Comment by jhkennedy** [comment]
@jrbourbeau I'm out tomorrow but could probably hit it next week. I'll assign this to me for now :-D
