### ISSUE TITLE
boto3 1.21.32 requires botocore<1.25.0,>=1.24.32, but you have botocore 1.31.64 which is incompatible.

### ISSUE THREAD

**Issue by yitai000** [nsidc/earthaccess#356]
install result:
Installing collected packages: botocore, earthaccess
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
boto3 1.21.32 requires botocore<1.25.0,>=1.24.32, but you have botocore 1.31.64 which is incompatible.
Successfully installed botocore-1.31.64 earthaccess-0.7.0

there is an error when import earthaccess:
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Input In [7], in <cell line: 1>()
----> 1 import earthaccess

File ~\AppData\Roaming\Python\Python39\site-packages\earthaccess\__init__.py:6, in <module>
      3 from importlib.metadata import version
      4 from typing import Any
----> 6 from .api import (
      7     auth_environ,
      8     collection_query,
      9     download,
     10     get_fsspec_https_session,
     11     get_requests_https_session,
     12     get_s3_credentials,
     13     get_s3fs_session,
     14     granule_query,
     15     login,
     16     open,
     17     search_data,
     18     search_datasets,
     19 )
     20 from .auth import Auth
     21 from .search import DataCollections, DataGranules

File ~\AppData\Roaming\Python\Python39\site-packages\earthaccess\api.py:5, in <module>
      3 import earthaccess
      4 import requests
----> 5 import s3fs
      6 from fsspec import AbstractFileSystem
      8 from .auth import Auth

File ~\AppData\Roaming\Python\Python39\site-packages\s3fs\__init__.py:1, in <module>
----> 1 from .core import S3FileSystem, S3File
      2 from .mapping import S3Map
      4 from ._version import get_versions

File ~\AppData\Roaming\Python\Python39\site-packages\s3fs\core.py:29, in <module>
     27 import aiobotocore
     28 import botocore
---> 29 import aiobotocore.session
     30 from aiobotocore.config import AioConfig
     31 from botocore.exceptions import ClientError, HTTPClientError, ParamValidationError

File ~\AppData\Roaming\Python\Python39\site-packages\aiobotocore\session.py:12, in <module>
      3 from botocore.session import (
      4     EVENT_ALIASES,
      5     ServiceModel,
   (...)
      8     copy,
      9 )
     11 from . import retryhandler
---> 12 from .client import AioBaseClient, AioClientCreator
     13 from .configprovider import AioSmartDefaultsConfigStoreFactory
     14 from .credentials import AioCredentials, create_credential_resolver

File ~\AppData\Roaming\Python\Python39\site-packages\aiobotocore\client.py:10, in <module>
      1 from botocore.awsrequest import prepare_request_dict
      2 from botocore.client import (
      3     BaseClient,
      4     ClientCreator,
   (...)
      8     resolve_checksum_context,
      9 )
---> 10 from botocore.compress import maybe_compress_request
     11 from botocore.discovery import block_endpoint_discovery_required_operations
     12 from botocore.exceptions import OperationNotPageableError, UnknownServiceError

ModuleNotFoundError: No module named 'botocore.compress'

**Comment by MattF-NSIDC** [comment]
I'm not sure I understand the report. We don't directly depend on `botocore`, that comes in through the `s3fs` dependency, which we have pinned fairly loosely (`s3fs = ">=2021.11, <2024"`).

`boto3`'s newest release is 1.29.x, have you tried that?
