### ISSUE TITLE
Zero granules are being reported for datasets with restricted access

### ISSUE THREAD

**Issue by danielfromearth** [nsidc/earthaccess#357]
### Challenge
When using `earthaccess` to search for "restricted" datasets — i.e., those that require an Earthdata login (EDL) to be part of an Access Control List (ACL) — zero granules are always being reported (`"granules found: 0"`) even though there are multiple granules in NASA's Common Metadata Repository (CMR).

### Desired functionality
When using `earthaccess` to search for "restricted" datasets, the correct number of granules should be reported when the user's EDL belongs to the appropriate ACL.

### Example
I encountered this challenge when searching for TEMPO data that is restricted based on Early Adopter and Science Team group memberships, and @betolink informed me that the same issue was encountered when searching for test ICESat-2 data. It is not possible to show a reproducible example that would work for everyone, because it depends on the EDL's access settings.

### Benefit
If restricted datasets can be made to work with `earthaccess`, its usability would be expanded to include early dataset testing.

**Comment by betolink** [comment]
Thanks @danielfromearth ! I think this has been a known issue for `earthaccess` and the fix would be to override the `hit()` method in the DataGranule class to use the authenticated sessions. I can work on this or if you like you can also open a PR. Thanks for reporting this!

**Comment by mfisher87** [comment]
Resolved by #358
