### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/earthaccess#369]
@betolink @jrbourbeau any reason to wait to cut a release?

**Comment by jrbourbeau** [comment]
I'd like to get 

- [ ] https://github.com/nsidc/earthaccess/pull/355
- [ ] https://github.com/nsidc/earthaccess/pull/354
- [ ] https://github.com/nsidc/earthaccess/pull/347

released. I'll set aside some time today to address any lingering comments folks have (IIRC they've all been minor suggestions).

**Comment by mfisher87** [comment]
@jrbourbeau If you can't get through those today, would you be OK if I cut a release anyway? @danielfromearth has an event coming up and requested a release by EOD today if we can!

**Comment by jrbourbeau** [comment]
Yeah, definitely. Sorry, I didn't mean to indicate that those PRs were blockers for releasing.
