### ISSUE TITLE
More Ruff rules

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/earthaccess#381]
Continuing discussion from here: https://github.com/nsidc/earthaccess/pull/372#discussion_r1410264309

PyUpgrade is one of my favorite rulesets, but we'll need to set it up with `target-version` of `3.8` to avoid upgrading our code out of compatibility with our target Pythons :)

**Comment by jhkennedy** [comment]
@MattF-NSIDC woops, we opened the same issue :rofl: . I added a list of potential rule in #383 . We could make this one specifically related to `pyupgrade` or close 383/this.

**Comment by MattF-NSIDC** [comment]
Let's close this one, yours has more detail :)
