### ISSUE TITLE
Release 0.8.1

### ISSUE THREAD

**Issue by jrbourbeau** [nsidc/earthaccess#387]
If there are no known blockers, I'd like to push out a release later today in order to get https://github.com/nsidc/earthaccess/pull/354 out in a released version of `earthaccess`

Anything else folks would like to get over the finish line before releasing?

**Comment by mfisher87** [comment]
Our backlog hasn't been in this great shape since I've seen it! :rocket: I can't think of anything to wait for. @jhkennedy ?
