### ISSUE TITLE
Remove binder? 

### ISSUE THREAD

**Issue by jrbourbeau** [nsidc/earthaccess#399]
Each PR gets a comment like this one https://github.com/nsidc/earthaccess/pull/397#issuecomment-1841113333 with a binder link. Though it looks like the binder is build is broken (see [this build](https://mybinder.org/v2/gh/jrbourbeau/earthaccess/f8cafefb8e1c9950fe2837e0e57e819cb9f2b32e) for an example). I'll propose we remove the PR comments until the builds are fixed.

**Comment by MattF-NSIDC** [comment]
Good catch. I got so used to those comments that I stopped seeing them :rofl:

**Comment by jhkennedy** [comment]
As of #821, Binder is working again, which begs the question do we want to re-enable the binder links? 

I personally don't care either way, but I lean *not* re-enabling them and closing this issue.

**Comment by mfisher87** [comment]
I'd be pro re-enabling if they worked like the ReadTheDocs links work :)
