### ISSUE TITLE
Release 0.8.2

### ISSUE THREAD

**Issue by jrbourbeau** [nsidc/earthaccess#404]
There have been a few bug fixes and maintenance updates since the last release that I'd like to get out before AGU. In particular 

- [x] https://github.com/nsidc/earthaccess/pull/391 
- [x] https://github.com/nsidc/earthaccess/pull/395
- [x] https://github.com/nsidc/earthaccess/pull/402

Anything else folks would like to see included?

**Comment by betolink** [comment]
I think this will also be included, right?

- [ ] https://github.com/nsidc/earthaccess/pull/394

Good timing for an end to end example with HLS data!  I'm fine with these changes. I'll be working on building a new hub image for Openscapes tomorrow. Hopefully we can have the new version out, thanks a lot for all the work @jrbourbeau @MattF-NSIDC @itcarroll et al !

**Comment by betolink** [comment]
Looks like we are ready! with the new tooling changes I'm hesitant to be the "release manager", I'm not sure if you have time to release today but if not I can try! @jrbourbeau
