### ISSUE TITLE
Filtering down spectral bands

### ISSUE THREAD

**Issue by jparal** [nsidc/earthaccess#409]
Hi, I am trying to download Harmonized Landsat Sentinel (HLS) dataset from earthdata using earthaccess. A single granule contains several spectral bands and mask(s) but for our use case, I only need a subset.
Is there a way for me to select a subset of the bands either using `search_data` API call or manually after getting the result of the search and before passing it onto `download()`?

Thx, J

**Comment by betolink** [comment]
Hi @jparal, if you know the name of the bands you want to filter you can definitely do it, here is an example after we get our results from `search_data()`
```python

filtered_urls = []

for granule in results:
    links = results[0].data_links()
    for link in links:
        if any(pattern in link for pattern in ["B02", "B01"]):
            filtered_urls.append(link)
            print(link)
            
earthaccess.download(links, "HLS_DATA")
```

This notebook from LP DAAC does something similar, https://nasa-openscapes.github.io/earthdata-cloud-cookbook/tutorials/Observing_Seasonal_Ag_Changes.html#finding-hls-data-using-earthaccess Let us know if this helps!

**Comment by jparal** [comment]
Thank you, this is helpful. I could do it manually as you suggested and wrap the results in some regex filter. Thx.
