### ISSUE TITLE
Improve UX for EDL password rotation

### ISSUE THREAD

**Issue by asteiker** [nsidc/earthaccess#412]
EDL is implementing mandatory 60 day password rotation beginning January 2024. Is there a way we could 1) identify that a user’s EDL password is expired programmatically, and then 2) pass a new password on through earthaccess? 

For 1), @MattF-NSIDC received guidance from the EDL team:

> Yes, the error message will indicate whether the password is correct but expired or if the credentials were invalid. A password reset email will also be sent automatically if a user with an expired password tries to authenticate.

> If you want, I can force-expire an account for you to test with in advance.

> That said, we recommend use of user tokens over user credentials wherever possible.

This may be a fairly simple change to surface this message and guide users towards urs to update their password. If we could get ahead of the password rotation mandate, this would really help out our users so they don't feel stuck using `earthaccess`.

**Comment by itcarroll** [comment]
Does the recommendation to use tokens over credentials mean earthaccess should have a way of persisting tokens?

**Comment by andypbarrett** [comment]
Is this still a necessary issue given NASA's postponement of pwd rotation

**Comment by asteiker** [comment]
Good catch @andypbarrett. I'd agree with closing this as OBE.
