### ISSUE TITLE
Get the list of all available datasets

### ISSUE THREAD

**Issue by giswqs** [nsidc/earthaccess#413]
I am working on integrating earthacess into [leafmap](https://github.com/opengeos/leafmap/issues/620) for interactive search and visualization of NASA Earth Data. Is it possible to get the list of all available datasets, such as short names, concept IDs, DOIs? The dataset list can be used as input to a dropdown list that allows users to select a dataset interactively.

**Comment by mfisher87** [comment]
Does this work for you? It may take a little time to return results.

```python
earthaccess.search_datasets(keyword="*")
```

This is a bit hacky :point_up: Any thoughts from maintainers on whether we should change the behavior when passing no arguments to return all collections? Currently:

```python
>>> earthaccess.search_datasets()
Warning: a valid set of parameters is needed to search for datasets on CMR
[]
```

**Comment by giswqs** [comment]
@mfisher87 Thank you for the trick! It only took 28 seconds to get the list. Not bad. I can create a GitHub Action to automatically update this list (in json and tsv formats) daily, similar to what I did for the [NASA-CMR-STAC](https://github.com/opengeos/NASA-CMR-STAC) repo. With the list readily available, it will be much faster for other packages to pull the list and use it as input to other workflows.   

![image](https://github.com/nsidc/earthaccess/assets/5016453/93a2c506-cc1e-421c-9f85-dbbf7771d836)

**Comment by mfisher87** [comment]
I love that idea :heart_eyes:

**Comment by mfisher87** [comment]
I opened an issue :point_up: to track the larger problem of intuitiveness. Thanks for your report! :heart:

**Comment by mfisher87** [comment]
That is so cool, nice work!
