### ISSUE TITLE
Query collections using 'instrument' and 'project'

### ISSUE THREAD

**Issue by mjami00** [nsidc/earthaccess#437]
I would like to see collections to be searchable using  'instrument' and 'project' parameters. Example is GEDI and OPERA projects.

**Comment by chuckwondo** [comment]
@betolink, you fixed this issue with this PR: #443, so this issue should be closed. You might also want to update the changelog for 0.9.0 so that #443 is referenced by this entry:

```plain
Search by instrument or project e.g. instrument="gedi"
```

**Comment by mfisher87** [comment]
I just updated the release notes in GitHub!
