### ISSUE TITLE
add linting of docstrings, using ruff

### ISSUE THREAD

**Issue by danielfromearth** [nsidc/earthaccess#454]
This came out of this separate docstring PR: https://github.com/nsidc/earthaccess/pull/448#issuecomment-1934742889#448 

Purpose: Enable linting of docstrings via ruff [this way](https://docs.astral.sh/ruff/faq/#does-ruff-support-numpy-or-google-style-docstrings).

@mfisher87

**Comment by mfisher87** [comment]
Thanks :)

FWIW I no longer log in to @MattF-NSIDC :) Having two accounts was too much of a pain so I consolidated to this one.

**Comment by mfisher87** [comment]
cc @Sherwin-14

**Comment by Sherwin-14** [comment]
@mfisher87  Hey, what convention do we choose here? the documentation gives some conventions like numpy or google should we proceed with these or choose some other convention?
