### ISSUE TITLE
Run `mkdocs` with `--strict` flag to catch e.g. docstring parameters out of sync with function parameters

### ISSUE THREAD

**Issue by mfisher87** [nsidc/earthaccess#456]
Opened from discussion: https://github.com/nsidc/earthaccess/pull/448#discussion_r1483663886

**Comment by jhkennedy** [comment]
For the docstring parameters, I suspect https://github.com/nsidc/earthaccess/issues/454 would solve that. There's warning MkDocs might raise as well, so it's not a bad idea to do both.

**Comment by mfisher87** [comment]
Resolved by #498
