### ISSUE TITLE
ci is annoying

### ISSUE THREAD

**Issue by betolink** [nsidc/earthaccess#458]
Every time a test on a PR or branch fails we get like 10000 e-mails, would it be good if we limit the e-mails to main? if possible.

**Comment by mfisher87** [comment]
I'm not experiencing this. What do the emails look like?

**Comment by betolink** [comment]
Maybe is only to the account that created the PR/branch? hopefully not all subscribers/maintainers are getting these every time... 

![Screenshot from 2024-02-08 21-48-22](https://github.com/nsidc/earthaccess/assets/717735/104c105a-93f6-47a5-8d25-3ae8b8bf3751)

**Comment by mfisher87** [comment]
Hmm...  in your notification settings, do you have anything set for "Customize email updates"? Or what about this setting?
![image](https://github.com/nsidc/earthaccess/assets/3608264/7c53f678-00d5-4c7a-a6bb-e701156b69b1)

**Comment by betolink** [comment]
Thanks for the tip!! I'm closing this issue.
