### ISSUE TITLE
Confusing output when running `earthaccess.download()` on undownloadable granules

### ISSUE THREAD

**Issue by yhyxzx** [nsidc/earthaccess#476]
Hello,

I am encountering an issue with the `earthaccess` library where I am able to successfully search for granules but unable to download the data. Here is the code I am using:

```python
import earthaccess

earthaccess.login()

results = earthaccess.search_data(
    short_name='AST_08',
    cloud_hosted=True,
    bounding_box=(119.5, 35.583, 121, 37.15),
    temporal=("2020-01", "2023-03"),
    count=10
)
files = earthaccess.download(results, "./local_folder")
```

The search function seems to work fine, as it finds 85 granules. However, when I attempt to download the data, the download process does not start and no files are downloaded to the specified local folder. The output from the download function is as follows:

Granules found: 85
Getting 10 granules, approx download size: 0.67 GB
QUEUEING TASKS | : 0it [00:00, ?it/s]
PROCESSING TASKS | : 0it [00:00, ?it/s]
COLLECTING RESULTS | : 0it [00:00, ?it/s]

I would appreciate any guidance or assistance in resolving this issue. Thank you in advance for your help.

Best regards, yhyxzx

**Comment by betolink** [comment]
Hi @yhyxzx looks like ASTER data is not downloadable as a file from the LP DAAC, as of now earthaccess does not support custom data services. This should be resolved when the data is migrated to the cloud, any thoughts on this @BriannaLind?

**Comment by mfisher87** [comment]
@betolink what do you think of re-titling this issue to "Confusing output when running `earthaccess.download()` on undownloadable granules"?

**Comment by betolink** [comment]
Makes sense

**Comment by torumitsutake** [comment]
I have the same issue.
I was able to download it when I tried it before, but have the specifications changed?

**Comment by mfisher87** [comment]
Perhaps we should alter the search functionality so granules that aren't downloadable aren't returned by default?

> I was able to download it when I tried it before, but have the specifications changed?

specifically with AST_08, or a different collection?

**Comment by torumitsutake** [comment]
Oh it my fault, I want to download `AST_L1Tv003` and now it works.

**Comment by mfisher87** [comment]
Great! Glad you got things working. Please open another issue or discussion if you run in to anything else or just want to share your user experience to help us improve :)
