### ISSUE TITLE
Define user .netrc directory [Feature request]

### ISSUE THREAD

**Issue by Rapsodia86** [nsidc/earthaccess#480]
Hello! 
I would like to suggest an option to provide a user-specific directory to *.netrc file. 
Now, it automatically looks into "C:\\User\\USERNAME\\.netrc" (if in Windows).
However, I do have that file stored in another location that I use for my other scripts, and I do not see a reason to have it duplicated and spread across the machine. 
How about adding the option in login like:
1) Looks into the default directory for the file: `earthaccess.login(strategy="netrc")`
2) Looks into user-specified location: `earthaccess.login(strategy="netrc", dir="DIRECTORY\SUBDIRECTORY\")`

Thanks!

**Comment by jhkennedy** [comment]
@Rapsodia86 would setting an environment variable work for you? For example:
```python
os.environ['NETRC_PATH'] = 'some/path/to/netrc'

earthaccess.login(strategy="netrc")
```
Would pick up your custom `netrc` at 'some/path/to/netrc'. 

That's only a three line change here, I think:
https://github.com/nsidc/earthaccess/blob/main/earthaccess/auth.py#L258

but plumbing an a new argument is a bit more work.

**Comment by Rapsodia86** [comment]
Yes,
I think that is a good solution. No need to reinvent the wheel.
There is a following question. If I set `os.environ['NETRC_PATH']` in the script, but then for some reason I use  `earthaccess.login(strategy="interactive",persist=true)` will it pick up the .netrc file from that new (custom) directory or it will create a new .netrc file in the default location?

Thanks again!

**Comment by jhkennedy** [comment]
@Rapsodia86 sounds good!

>  If I set os.environ['NETRC_PATH'] in the script, but then for some reason I use earthaccess.login(strategy="interactive",persist=true) will it pick up the .netrc file from that new (custom) directory or it will create a new .netrc file in the default location?

How would you like it to work? Either could be supported, but I'd lean toward if the `NETRC`/`NETRC_PATH` (whichever name we chose) variable is set, we would write/update the custom one when doing `earthaccess.login(strategy="interactive",persist=true)`

**Comment by Rapsodia86** [comment]
Yes, I agree! The consistent usage of `NETRC/NETRC_PATH` will allow to avoid confusion! Great:)

**Comment by mfisher87** [comment]
Excellent decision, folks ;)

**Comment by chuckwondo** [comment]
FYI, we should simply be using `requests.utils.get_netrc_auth`, which conveniently takes care of all of this for us. See https://github.com/psf/requests/blob/v2.32.3/src/requests/utils.py#L204.

**Comment by cboettig** [comment]
fwiw, in [GDAL this path](https://gdal.org/en/latest/user/configoptions.html) is called:

```
GDAL_HTTP_NETRC_FILE=<filename>: (GDAL >= 3.7.0) Sets the location of a .netrc file.
```

In libcurl it is [CURLOPT_NETRC_FILE](https://curl.se/libcurl/c/CURLOPT_NETRC_FILE.html)
