### ISSUE TITLE
Add `logging` module usage in place of `print` calls

### ISSUE THREAD

**Issue by chuckwondo** [nsidc/earthaccess#511]
There are a number of calls to `print` throughout the code base that should probably be replaced with appropriate calls to the standard `logging` library.

**Comment by botanical** [comment]
Hello 👋 I opened a PR here https://github.com/nsidc/earthaccess/pull/566/. I'm unable to assign this to myself but I did check the open PRs and it doesn't look like anyone has addressed this issue yet.

**Comment by mfisher87** [comment]
Resolved by #566 , thank you @botanical !
