### ISSUE TITLE
We don't have maintainer documentation

### ISSUE THREAD

**Issue by mfisher87** [nsidc/earthaccess#537]
#521 proposed a maintainer doc, but that would be an addition, not a refactor. This ticket is for the new documentation.

Related: #529 ,  #573 

* How to become a maintainer or triager?
    * Need better text, but something along the lines of be involved in our community and ask if you're interested.
    * Also, if you're interested in helping managing issues with labels and interacting with incoming requests, you can have a "triager" role!
* What is required of maintainers?
    * No time obligation, we understand our ability to commit can fluctuate, but communicate openly.
    * Yes obligation to team culture (e.g. link to [Openscapes team culture page](https://openscapes.github.io/series/core-lessons/team-culture.html), [and recorded psychological safety talk](https://www.youtube.com/watch?v=rzi-qkl8u5M))
    * More???
*  What processes do maintainers follow beyond regular contributing processes?
    * Labeling. Specifically call out "good first issue"
    * Creating welcoming environment when communicating with contributors (issue / PR / discussion posters).
    * Reviewing and merging.
    * Releasing (documented in contributor guide already, we should move in to the maintainer guide).
* ???

**Comment by Sherwin-14** [comment]
Hey are we looking at something similar to this https://www.pygmt.org/dev/maintenance.html.?

**Comment by mfisher87** [comment]
That looks amazing. In addition to answering the questions above (I'll add a bit of prose to the issue description), that maintainer guide includes the policy we're considering adopting in #573 , so we could knock both issues down at once here.

**Comment by chuckwondo** [comment]
> That looks amazing. In addition to answering the questions above (I'll add a bit of prose to the issue description), that maintainer guide includes the policy we're considering adopting in #573 , so we could knock both issues down at once here.

They even have a more detailed page regarding [Minimum Supported Versions](https://www.pygmt.org/dev/minversions.html)

**Comment by mfisher87** [comment]
We now have a maintainer doc thanks to @Sherwin-14's amazing work! :tada:
