### ISSUE TITLE
prettier's pre-commit mirror is archived and keeps trying to upgrade us to alpha version

### ISSUE THREAD

**Issue by mfisher87** [nsidc/earthaccess#555]
---

_Originally posted by @chuckwondo in https://github.com/nsidc/earthaccess/issues/446#issuecomment-2084844024_

> What do we think is the way forward?
> 
> * Turn off auto-updates
> * Edit the auto-update PRs before merging to remove alpha bumps
> * Use alpha prettier
> * ???

In this case, I'd say we remove https://github.com/pre-commit/mirrors-prettier because it has been archived.

There aren't many alternatives for yaml formatting. A couple of others are also archived, such as this one: https://github.com/mmlb/yamlfmt

Perhaps we go with this one: https://github.com/google/yamlfmt

**Comment by chuckwondo** [comment]
> In this case, I'd say we remove https://github.com/pre-commit/mirrors-prettier because it has been archived.
> 
> There aren't many alternatives for yaml formatting. A couple of others are also archived, such as this one: https://github.com/mmlb/yamlfmt
> 
> Perhaps we go with this one: https://github.com/google/yamlfmt

Anybody have any preference or alternatives to suggest here?

**Comment by mfisher87** [comment]
Not strong preference. Another option that I recently found out isn't so difficult: create our own pre-commit mirror, and omit the alpha versions. That may be lower lift than switching tools.

**Comment by trallnag** [comment]
> Not strong preference. Another option that I recently found out isn't so difficult: create our own pre-commit mirror, and omit the alpha versions. That may be lower lift than switching tools.

By "pre-commit mirror" do you mean the prettier mirror repo?

**Comment by mfisher87** [comment]
I have used this pre-commit mirror for prettier on another project and it worked really well: https://github.com/rbubley/mirrors-prettier

It's the same as the archived official mirror, except only includes releases up to 3.x.
