### ISSUE TITLE
README needs "Why earthaccess?" and "one-liner install"

### ISSUE THREAD

**Issue by betolink** [nsidc/earthaccess#561]
I think the last documentation PR https://github.com/nsidc/earthaccess/pull/498 removed too much information from the README, in particular the justification and how to install it. 

* "Why earthaccess?
* "How to install earthaccess"

We should try to have one source of true but people usually see a README and expect to get a sense of what the project is about (context) and some basic instructions (how to install it and perhaps an example). I think this is related to how well-known a project is, once that a project gets big enough they prioritize external docs (even with their own domains like https://docs.xarray.dev/en/stable/) but I feel like until we are at that level maybe we should not forget that a README is the first point of entry to a library. Some of the concepts I find relevant come from [Art of README](https://github.com/hackergrrl/art-of-readme)

I'm happy to discuss this further!

**Comment by Sherwin-14** [comment]
@mfisher87 @betolink  Hey, do you guys have any specific opinions regarding this? If not, then can I take this issue up?
