### ISSUE TITLE
Remove the dask tutorial notebook for now

### ISSUE THREAD

**Issue by mfisher87** [nsidc/earthaccess#569]
[The dask tutorial notebook](https://github.com/nsidc/earthaccess/blob/main/docs/tutorials/dask.ipynb) is not linked in the Mkdocs nav. Relevant discussion: https://github.com/nsidc/earthaccess/pull/568#discussion_r1597673850

* Why was it removed from the nav? _It wasn't! It was added as a comment to remind us to add it to the nav later when it was more complete._
* Do we want to bring it back? _Yes, but in a different form._
* What needs to be done to bring it back? _@betolink working on it as part of `smart_open` (#527) work

## Decision: Remove it for now!

**Comment by mfisher87** [comment]
The tutorial was never added as a nav item, it was always commented out: https://github.com/nsidc/earthaccess/commit/dab9da4b290424dc4de2bd2212a8d1212019b947

@betolink can you shed some light on this?

**Comment by betolink** [comment]
This was an initial toy example with Dask, I'm working on a version that works independently of Coiled but I don't think it will be ready until next month, hopefully by then we'll have `smart_open=True` released.

**Comment by mfisher87** [comment]
Should we remove this notebook so it can be replaced with the Coiled-independent version later?

**Comment by betolink** [comment]
I think so.

**Comment by Sherwin-14** [comment]
@mfisher87 Hey Matt, is this issue still relevant? If yes, do you any specific opinions regarding this?
