### ISSUE TITLE
Refactor loops in tests to be parametrized

### ISSUE THREAD

**Issue by botanical** [nsidc/earthaccess#578]
Some tests can be updated to use [pytest.parametrize](https://docs.pytest.org/en/7.1.x/example/parametrize.html), such as https://github.com/nsidc/earthaccess/blob/main/tests/integration/test_auth.py#L83-L98

**Comment by mfisher87** [comment]
cc @Sherwin-14

**Comment by mfisher87** [comment]
Hey @Sherwin-14, not 100% sure if this answers your question, but we're looking to replace the for loop in the linked test with a `@pytest.parametrize` decorator as shown in the docs linked in the top-level post. This will increase the total number of tests, but there will be less assertions in each of the affected test. Does this help?

**Comment by Sherwin-14** [comment]
> Hey @Sherwin-14, not 100% sure if this answers your question, but we're looking to replace the for loop in the linked test with a `@pytest.parametrize` decorator as shown in the docs linked in the top-level post. This will increase the total number of tests, but there will be less assertions in each of the affected test. Does this help?

If I understand correctly, we might need to break these test functions and replace the for loop's with `@pytest.parametrize` decorator. This would result in 2 tests resulting from one single broken test?

**Comment by mfisher87** [comment]
There would still be one test function, but the decorator would allow that test to run multiple times with different parameters, in other words different input data and different expected outputs. With this method, we specify the test logic once in the function, and then represent the different parameters as a data structure that we pass to the `@pytest.parametrize` decorator.

**Comment by Sherwin-14** [comment]
@mfisher87 Hey can you assign me this one?

**Comment by chuckwondo** [comment]
Fixed by #736
