### ISSUE TITLE
code of conduct not rendering properly

### ISSUE THREAD

**Issue by JessicaS11** [nsidc/earthaccess#591]
I'm hoping I'm the only one with this problem, but https://earthaccess.readthedocs.io/CODE_OF_CONDUCT.md isn't rendering properly for me (tried it in Firefox and Safari). Can somebody else check?

**Comment by jhkennedy** [comment]
It's also not rendering for me on linux with either Firefox or Chrome

**Comment by jhkennedy** [comment]
Scrolling all the way down, it's because of an HTTP 404 error. :thinking:

**Comment by jhkennedy** [comment]
@JessicaS11 how are you getting to that page? Is it linked somewhere? AFICT we don't include it in the docs

**Comment by jhkennedy** [comment]
Oh, I bet it's this:
https://github.com/nsidc/earthaccess/blob/main/docs/contributing/index.md?plain=1#L9

yes, that will be a broken link -- the MkDocs context is not the repository root but the docs folder, and so it's looking for the COC at `docs/CODE_OF_CONDUCT.md`

**Comment by JessicaS11** [comment]
> how are you getting to that page?

From the docs: https://earthaccess.readthedocs.io/en/latest/contributing/ (there's a link in like the second paragraph to the COC). FWIW, I may have naively included the 404 link in our proposal (having grabbed it from the docs and not realized it hadn't loaded until I just went to close the tab and couldn't figure out what I was looking at!).

**Comment by jhkennedy** [comment]
@JessicaS11 yes, that link is located in the source I linked to above -- PR incoming.

**Comment by jhkennedy** [comment]
@JessicaS11 did you include `https://https://earthaccess.readthedocs.io/CODE_OF_CONDUCT.md` directly in the proposal?

I'll look into a redirect
