### ISSUE TITLE
Make `pyproject.toml` use PEP621 conventions to specify dependencies

### ISSUE THREAD

**Issue by mfisher87** [nsidc/earthaccess#617]
For example, we have `[tools.poetry.dependencies]` instead of a `dependencies` key under `[project]`. I think we should use PEP621-compliant configuration here regardless of whether we use Poetry or not.

Related: #374

**Comment by Sherwin-14** [comment]
@mfisher87 Hey how would you like to approach this issue? What specifics should I look into or understand before I proceed forward.

**Comment by mfisher87** [comment]
All of this config is poetry-specific: https://github.com/nsidc/earthaccess/blob/main/pyproject.toml#L37-L103

Instead, we should be using the plan `dependencies` and `optional-dependencies` data structures (https://peps.python.org/pep-0621/#dependencies-optional-dependencies). Like the [example in the PEP621 doc](https://peps.python.org/pep-0621/#example), almost everything should be under the `project` top-level key. The poetry "extras" section is just another way of expressing an optional dependency group. So we can take all 3 of the poetry-specific sections and combine them to PEP621-standard `dependencies` and `optional-dependencies` sections.

**Comment by Sherwin-14** [comment]
@mfisher87 So are we switching to setuptools? What do you think about this?

**Comment by mfisher87** [comment]
I'm personally for this, but I think we need more input from the rest of the team. Our next hack day may be a good time to chat in real-time to make a decision.

**Comment by itcarroll** [comment]
Another one fixed by #733! (And I'm not through yet.)
