### ISSUE TITLE
Problem downloading SWOT PIXCVec files

### ISSUE THREAD

**Issue by cordmaur** [nsidc/earthaccess#621]
I'm using `earthaccess` to download PIXC and PIXCVec SWOT products.
For the same args (bbox and time range), the PIXCVec is returning several files that are not within the AOI. 

Here is an example: 
```
results = earthaccess.search_data(
    short_name='SWOT_L2_HR_PIXC_2.0', 
    temporal=('2023-11-06', '2023-11-07'), 
    bounding_box=AOI.bounds
)

Granules found: 1
```
```
results = earthaccess.search_data(
    short_name='SWOT_L2_HR_PIXCVec_2.0', 
    temporal=('2023-11-06', '2023-11-07'), 
    bounding_box=AOI.bounds
)

Granules found: 115
```

When we check for the results, we can see that several PIXVec files have  `Spatial Extent` incorrectly (imho) set to -180, -90, 180, 90, and that's causing this discrepancy in the search. 

![image](https://github.com/podaac/tutorials/assets/19617404/748cc5ff-f01e-42fd-8f66-a1823e43c3d4)

I don't know if this is the best channel for such issue.

**Comment by mfisher87** [comment]
Thanks for reporting this issue! This is at least a good place to start :) Unfortunately, we can't actually fix the problem. I think the best place to report this would be to PO DAAC's user support: `podaac@podaac.jpl.nasa.gov`

**Comment by itcarroll** [comment]
CC @cassienickles

I think PO.DAAC fixed the metadata problem. @cordmaur did not give us an AOI, but the following yields only a single result.
```
results = earthaccess.search_data(
    short_name='SWOT_L2_HR_PIXCVec_2.0',
    temporal=('2023-11-06', '2023-11-07'), 
    point=(29.2, -25.4),
)
```
And it does not have global extent:
```
results[0]["umm"]["SpatialExtent"]
{'HorizontalSpatialDomain': {'Geometry': {'GPolygons': [{'Boundary': {'Points': [{'Latitude': -25.11548682980479,
        'Longitude': 28.80353356231359},
       {'Latitude': -25.85642615296355, 'Longitude': 28.80353356231359},
       {'Latitude': -25.85642615296355, 'Longitude': 29.609624187217776},
       {'Latitude': -25.11548682980479, 'Longitude': 29.609624187217776},
       {'Latitude': -25.11548682980479, 'Longitude': 28.80353356231359}]}}]},
  'Track': {'Cycle': 6, 'Passes': [{'Pass': 152, 'Tiles': ['199R']}]}}}
```
So I assume there are no longer *any* global extent records for that temporal range.
