### ISSUE TITLE
Endorse a finite number of package managers and document how to use them for contributing, including limitations

### ISSUE THREAD

**Issue by mfisher87** [nsidc/earthaccess#741]
We have a conda dev environment specification, but we don't really document how to use it. For a pure python project, I expect `pip install --editable .[dev,...]`, but we've set up our project for poetry development environment, and our contributing doc doesn't say how to use it. What package managers do we want to endorse / encourage and document for our contributors?

Limitations: For example, our `environment-dev.yml` isn't perfectly up to date. Let's document that or change the file so that it doesn't need to be kept up to date, as suggested by @jhkennedy [here](https://github.com/nsidc/earthaccess/issues/614#issuecomment-2190226599)

Extracted from #449

**Comment by itcarroll** [comment]
Can we say this is closed by #733, which blessed and documented `nox`, `python -m venv`, and `conda`?

**Comment by mfisher87** [comment]
I'm good with that :)
