### ISSUE TITLE
Update integration tests to use pytest conventions

### ISSUE THREAD

**Issue by Sherwin-14** [nsidc/earthaccess#743]
Integration tests have been failing silently for some time (https://github.com/nsidc/earthaccess/pull/738). In the course of adding new integration tests (https://github.com/nsidc/earthaccess/pull/736), we found some errors that were not reporting very much information, presumably either because [the code that's generating the errors](https://github.com/nsidc/earthaccess/blob/e7cb5bc948a88217b521ef76f7c93c9c384e9e3f/tests/integration/test_onprem_open.py#L15-L62) are not following pytest conventions.

1. Tests which `import assertions` and call for example `assertions.assertTrue(x)` should be updated to builtin assertions, for example `assert x is True`.
2. Tests which do setup at the module level should be updated to use [fixtures](https://docs.pytest.org/en/6.2.x/fixture.html)

**Comment by mfisher87** [comment]
This test file is a good example: https://github.com/nsidc/earthaccess/blob/main/tests/integration/test_onprem_download.py#L51-L63 Looks like most of the integration test files have this problem, but not all (e.g. `test_auth.py` looks OK).

**Comment by Sherwin-14** [comment]
> This test file is a good example: https://github.com/nsidc/earthaccess/blob/main/tests/integration/test_onprem_download.py#L51-L63 Looks like most of the integration test files have this problem, but not all (e.g. `test_auth.py` looks OK).

Yeah but I guess the granules function here is used as a setup and it has already been fixturized(If that's a term).  Also this means that we juts need to update codeblocks like the above example, and not to tinker with the other `assertions.assertTrue(x)` expressions.

**Comment by mfisher87** [comment]
I wouldn't describe `get_sample_granules` or the auth store setup as "fixturized" at the moment, at least under Pytest conventions, since they're not using a fixture decorator (and the auth stuff is bare at the module level). Have you checked out this doc yet? https://docs.pytest.org/en/6.2.x/fixture.html

The pytest fixture decorators provide advanced functionality for managing the fixture's lifecycle or scope. That way, we don't need to repeat behavior unnecessarily (we do this same credential-reading stuff at the module level in several files in addition to `test_onprem_download.py`, but we only need to do it once: https://github.com/nsidc/earthaccess/blob/2df1da91925e81e50f49b289020a48aaad0ba5de/tests/integration/test_onprem_open.py#L50-L62), and we get better reporting from pytest to help us understand what's going on :)

**Comment by Sherwin-14** [comment]
Oh there seems to be some misunderstanding here! I was talking about the `granules` function in `test_kerchunk.py`  that is fixturized at the moment. So I was basically asking for one more example of  a setup process that is not fixturized uptill now.

**Comment by mfisher87** [comment]
Gotcha, thanks for clarifying! Just double-checking, do you have the info you need now?

**Comment by Sherwin-14** [comment]
Not yet (🤣). I just need an example of the setup function that is not fixturized yet!

**Comment by mfisher87** [comment]
In this case, it's not a function, it's the module-level code I linked above which creates an `Auth` and `Store` object. Does that make sense?

**Comment by Sherwin-14** [comment]
The `auth` and `store` objects can be considered as  setup's, is that what you are implying? Also I think that the `conftest.py`  file should contain all the fixturized functions. So I am thinking of putting all the fixturized functions in that file, would that be fine with you?

**Comment by mfisher87** [comment]
> The `auth` and `store` objects can be considered as setup's, is that what you are implying?

Correct!

> Also I think that the `conftest.py` file should contain all the fixturized functions. So I am thinking of putting all the fixturized functions in that file, would that be fine with you?

Sounds great :) Thanks again @Sherwin-14 for your work!

**Comment by Sherwin-14** [comment]
Hey, In that case may be grouping them into a function and then fixturizing it can be a solution isn't it? or Am I missing something?

**Comment by mfisher87** [comment]
Yes, exactly :) I don't think you're missing anything!
