### ISSUE TITLE
EDL tokens not being revoked and regenerated as expected

### ISSUE THREAD

**Issue by mfisher87** [nsidc/earthaccess#764]
> First of all thanks for this library, it is very helpful for us! I have a question which is touching this issue. When we are doing `earthaccess.search_data()` we are login in  via [environment variables](https://github.com/nsidc/earthaccess/blob/7a79ea5f1eb752d9050f58e3e0c2813a4409626d/docs/howto/authenticate.md?plain=1#L40). So far so good, under https://urs.earthdata.nasa.gov/users/username/user_tokens we can see that two new tokens are created. I guess these are [CMR Tokens](https://cmr.earthdata.nasa.gov/access-control/site/docs/access-control/api.html)? However, these tokens expire after 2 months and are not re-created and when we continue to use `earthaccess` we are getting `RuntimeError('{"errors":["Token [Bearer eyJXXXI4SIQ] has expired. Note the token value has been partially redacted."]}'`. This is solved by just deleting the Bearer Tokens, which triggers a re-creation.

_Originally posted by @fwfichtner in https://github.com/nsidc/earthaccess/issues/484#issuecomment-2230454111_
            

> Token regeneration is not automatic, actually is not part of the top level API. It could be automatic if we encounter an expired token, as of now one can do this:
>
> ```python
> import earthaccess
>
> auth = earthaccess.login()
>
> auth.refresh_tokens()
> ```

_Originally posted by @betolink in https://github.com/nsidc/earthaccess/issues/484#issuecomment-2231553599_

To implement this, I think we need to look for this specific response from EDL and do a token refresh when we see it.

**Comment by fwfichtner** [comment]
Thanks for opening this issue, I saw the part of the code [you linked](https://github.com/nsidc/earthaccess/issues/484#issuecomment-2230933621) and wondered why that did not work as expected for us.
Are you able to reproduce the behaviour?

**Comment by mfisher87** [comment]
I haven't had the opportunity to try to reproduce yet. If someone else can help with reproduction, that'd be great! A lot on my plate at the moment :)
