### ISSUE TITLE
Deprecate `Store.get_s3fs_session`, expose under new name: `Store.get_s3_filesystem`

### ISSUE THREAD

**Issue by chuckwondo** [nsidc/earthaccess#766]
The method `Store.get_s3fs_session` is misleading because it does _not_ return any kind of "session" object. Rather, it returns an instance of `s3fs.S3FileSystem`, so the method should be renamed to properly reflect the type of object it returns.

I propose we deprecate `Store.get_s3fs_session` (along with all other places where it is surfaced through functions of the same name) and replace it (and other methods/functions named the same) with the name `get_s3fs_filesystem`.

**Comment by mfisher87** [comment]
Or `get_s3_filesystem` since `fs` already stands for file system?

**Comment by chuckwondo** [comment]
> Or `get_s3_filesystem` since `fs` already stands for file system?

Yep, I was actually going to suggest that originally for that same reason, so I'm happy to use that name instead.

**Comment by Sherwin-14** [comment]
@mfisher87 Hey I want to have a look into this one.

**Comment by chuckwondo** [comment]
@Sherwin-14, I'm going to pick up this issue. I've been dealing with this very problem in other work that I'm doing, and the solution is not obvious, nor even documented.

**Comment by chuckwondo** [comment]
> ~@Sherwin-14, I'm going to pick up this issue. I've been dealing with this very problem in other work that I'm doing, and the solution is not obvious, nor even documented.~
> 

Sorry, I was thinking about #765

**Comment by mfisher87** [comment]
Remember for the purpose of the changelog that this is a breaking change :)

**Comment by chuckwondo** [comment]
> Remember for the purpose of the changelog that this is a breaking change :)

If we deprecate the existing methods/functions, it's not a breaking change until we actually _remove_ the deprecated items, no?

**Comment by mfisher87** [comment]
Correct, if we go down that path we should leave deprecation warnings! I did not pay close enough attention to your use of "deprecate" in the issue description and was just reading the title :)

**Comment by chuckwondo** [comment]
> Correct, if we go down that path we should leave deprecation warnings! I did not pay close enough attention to your use of "deprecate" in the issue description and was just reading the title :)

Right, thanks for clarifying that in the issue title. This raises another question. Have we define how we deprecate things? In terms of how deprecations appear in the changelog, our changelog conventions cover that, but how about a coding guideline for actually implementing a deprecation?

**Comment by mfisher87** [comment]
Yeah, that sounds like something that should be in the contributing guide! Great call. Beyond e.g. "use the built-in `DeprecationWarning` exception type", what things would you imagine should be there? A style guide for the warning message itself?

**Comment by chuckwondo** [comment]
See thread in PR #768

**Comment by chuckwondo** [comment]
Fixed by #768
