### ISSUE TITLE
Update contributing doc to include instructions to set up Earthdata Login credentials on a fork so integration tests can run on PRs

### ISSUE THREAD

**Issue by mfisher87** [nsidc/earthaccess#773]
Should probably be the first step we instruct contributors to do after forking.

**Comment by Sherwin-14** [comment]
@mfisher87 Would'nt this encompass just a block(having the username and password) with directions?

**Comment by mfisher87** [comment]
![image](https://github.com/user-attachments/assets/ef412928-0b19-4b68-889a-53044b447ade)

I'm thinking we can maybe make it a sub-bullet of the second bullet on the contributing document?

**Comment by mfisher87** [comment]
:bow: Thanks, Sherwin!

**Comment by Sherwin-14** [comment]
Is this one urgent or is it something we can hold for now?

**Comment by mfisher87** [comment]
I don't feel that it's urgent :)

**Comment by mfisher87** [comment]
Will be OBE by #811

**Comment by chuckwondo** [comment]
OBE by #818

**Comment by mfisher87** [comment]
Thank you, Chuck! This work will also be useful to icepyx :)

cc  @JessicaS11
