### ISSUE TITLE
Links broken in docs

### ISSUE THREAD

**Issue by trey-stafford** [nsidc/earthaccess#778]
The links in the note on this page are broken and are not formatted in a very readable way: https://earthaccess.readthedocs.io/en/latest/user_guide/authenticate/.

Resolved by https://github.com/nsidc/earthaccess/pull/777

**Comment by trey-stafford** [comment]
Found some additional links that are broken, which are commented on in the associated PR. Resolving those with this issue/PR as well.

**Comment by mfisher87** [comment]
Amazing, thank you Trey! :bow:
