### ISSUE TITLE
Broken link: "Introducing NASA earthaccess"

### ISSUE THREAD

**Issue by mfisher87** [nsidc/earthaccess#779]
> I also just noticed another broken link on this page: https://earthaccess.readthedocs.io/en/latest/howto/search-granules/ ("Introducing NASA earthaccess" tutorial link).

_Originally posted by @trey-stafford in https://github.com/nsidc/earthaccess/issues/777#issuecomment-2259084223_

**Comment by mfisher87** [comment]
Not sure what's up there, thanks @trey-stafford ! Our docs used to be built on GitHub Pages, but we've since shut that down in favor of RTD (#363). Can we lint our docs for links to the old docs?

I think this tutorial is gone. I think we can remove this link from this sentence, so we only are pointing users to the portal and API docs.

**Comment by Sherwin-14** [comment]
@mfisher87 Can I take this up?

**Comment by mfisher87** [comment]
Absolutely, thanks so much!
