### ISSUE TITLE
This needs a documentation for usage

### ISSUE THREAD

**Issue by andypbarrett** [nsidc/earthaccess#79]
I'm thinking of a readthedocs page

**Comment by betolink** [comment]
Hey Andy, what about this as a start: https://nsidc.github.io/earthdata/ and https://earthdata.readthedocs.io/en/latest/ @andypbarrett ?

**Comment by betolink** [comment]
There is a new project that will serve as a gallery for different use cases, for now is under my personal username but I'll transfer it once is ready for prime time. I think it should be there in a month or so https://github.com/betolink/earthaccess-gallery

**Comment by andypbarrett** [comment]
We have a readthedocs page.
