### ISSUE TITLE
Running integration tests using nox

### ISSUE THREAD

**Issue by betolink** [nsidc/earthaccess#815]
### Is this issue already tracked somewhere, or is this a new report?

- [X] I've reviewed existing issues and couldn't find a duplicate for this problem.

### Current Behavior

`nox -s integration_tests`  is not configured in nox.

### Expected Behavior

`nox -s integration_tests` should run locally and in CI (see #810). 

### Steps To Reproduce

1. clone the repo
2. 
3. run `nox -s integration_tests` 

### Environment

```markdown
- OS: Ubuntu 22.04
- Python: 3.11
```

**Comment by chuckwondo** [comment]
@betolink, thanks for pointing this out. The missing "docs" nox session was an oversight on the reviewers (myself included) of that recent PR.

I think the docs and integration tests additions should be 2 separate issues though. Would you mind splitting this?

**Comment by mfisher87** [comment]
My bad on that one y'all!

**Comment by chuckwondo** [comment]
> I think the docs and integration tests additions should be 2 separate issues though. Would you mind splitting this?

@betolink ^^^

**Comment by betolink** [comment]
😅  @chuckwondo Let's do that, both will need a real EDL account... maybe for now we just use the one we've been using on CI and add a section in how to run the tests locally using our own account (with a big caveat warning about having all the EULAs approved beforehand)
