### ISSUE TITLE
the `search_data` function raises (unhelpfully) when no results are found

### ISSUE THREAD

**Issue by itcarroll** [nsidc/earthaccess#816]
```
results = earthaccess.search_data(
    short_name='SWOT_L2_HR_PIXCVec_2.0',
    temporal=('2023-11-06', '2023-11-07'), 
    point=(0, 0),
)
```
should return `[]` but instead raises an `IndexError` because
https://github.com/nsidc/earthaccess/blob/bb553e17c98ea3ef4d07316ea651cca02af71713/earthaccess/search.py#L470-L472

assumes `response` is not empty

If my claim that returning `[]` is agreeable, then we better also make sure that `earthaccess.download` doesn't choke when given `[]`.

**Comment by chuckwondo** [comment]
@itcarroll, I think this is a dup of https://github.com/nsidc/earthaccess/issues/526

**Comment by mfisher87** [comment]
Side thought, perhaps when we return an empty list we should log a warning?
