### ISSUE TITLE
Development Setup Instructions Not Working on Windows

### ISSUE THREAD

**Issue by ebolch** [nsidc/earthaccess#858]
When setting up my development environment in Windows using the [instructions](https://earthaccess.readthedocs.io/en/latest/contributing/development/). The main issue was that the `conda/mamba` installation would not complete. @jhkennedy seems to think it's the `docs` portion of the `pip` installs. 

I was able to get the environment created using the following, but I did have some errors when trying to run the tests with `nox`:

```{cmd}
mamba create -n earthaccess python=3.12 pip
```
```{cmd}
python -m pip install -e ".[dev]"
```

When running the tests with nox, the session was susccessful, but one test did fail:
```{cmd}
nox -s tests
```

![image](https://github.com/user-attachments/assets/ae8d7771-3fab-47ae-b23c-6c24ce89c408)

On a separate note, it was somewhat difficult to get `pipx` and `nox` installed because I had to manually add them to the PATH.

Maybe some separate Windows instructions are needed. I'm more than happy to help create the documentation if I can get everything up and running.

**Comment by chuckwondo** [comment]
Your editable install should be this (taken from the instructions page you linked):

```
python -m pip install --editable ".[dev,test,docs]"
```

Since you didn't include `test`, that's likely why not all tests were successful.

Try the above command and rerun tests to see if they all pass.

**Comment by jhkennedy** [comment]
> Since you didn't include test, that's likely why not all tests were successful.

@chuckwondo the tests in the example above were run with `nox` which sets up an isolated environment for tests, so the `test` dependencies were installed.

> Your editable install should be this (taken from the instructions page you linked):
> ```
> python -m pip install --editable ".[dev,test,docs]"
> ```

That _did not_ work on Windows; `pip` hung trying to resolve the environment. We did confirm on Windows that installing `dev,test` does work, so it's likely something in `docs` that was the problem for Windows.

**Comment by ebolch** [comment]
I went back and ran the `mamba` setup again. It worked, but took a VERY long time (~10 mins). Before I was under the impression that it just froze, but I guess that was not the case. 

Unsure this is associated with Windows, but my `nox` run of the tests is still failing on `tests\unit\test_store.py`.

**Comment by jhkennedy** [comment]
Okay, it looks like everything is working fine on Windows, it's just *slow*. 

Similarly, the pytest failure is marked as "expected" (xfailed) and if pytest is invoked with the `-r` option, we'd see:
```
XFAIL tests/unit/test_store.py::test_earthaccess_file_getattr - This test reproduces a bug (#610) which has not yet been fixed.
```

I'm going to close this issue, but I'll open a PR to make sure we're passing the `-rx`  (or maybe `-rxXs` ) so we propagate known failure reasons up to the pytest summary.
